<?php
// teacher_views/dashboard_content.php
// This file is included by teacher_dashboard.php and has access to its variables
// $teacher_username, $current_language_name_for_selected_date_display, $total_languages, $days_set_this_month
// Also now has $chart_datasets_json and $chart_labels_json for the chart data
?>
<style>
    /*
    * This style block is placed directly in dashboard_content.php because it specifically
    * targets the elements generated by the calendar logic within this file.
    */
    .calendar-day { /* Base styles for all calendar day cells */
        display: flex;
        justify-content: center;
        align-items: center;
        position: relative;
        padding: 0.5rem; /* Tailwind's p-2 */
        text-align: center;
        border-radius: 0.375rem; /* Tailwind's rounded-md */
        background-color: #edf2ff; /* Tailwind's gray-200 */
        color: #4a5568; /* Tailwind's gray-700 */
        transition: background-color 0.1s ease-in-out, color 0.1s ease-in-out;
        min-height: 2.5rem; /* Ensure a minimum height for cells */
        box-sizing: border-box;
    }

    .calendar-day.empty { /* For cells not representing any day */
        background-color: transparent;
        color: transparent;
    }

    .calendar-day.active-month {
        /* background-color: #e2e8f0; Slightly different gray if needed */
        color: #2d3748; /* Tailwind's gray-800 */
    }

    .calendar-day.inactive-month {
        background-color: #f7fafc; /* Tailwind's gray-50 for muted days */
        color: #a0aec0; /* Tailwind's gray-400 for muted day numbers */
    }

    /* Styles for the current day highlight (blue circle effect) */
    .calendar-day.current-day {
        background-color: transparent !important; /* Day cell itself is transparent */
        border: none !important;
        position: relative; /* For positioning the pseudo-element */
        z-index: 1;
        font-weight: 600; /* Make current day number bold */
    }

    .calendar-day.current-day::before { /* The blue circle */
        content: '';
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%); /* Center the circle */
        width: 2.2rem;  /* Size of the circle */
        height: 2.2rem; /* Size of the circle */
        border-radius: 50%; /* Make it circular */
        background-color: #4299e1; /* Blue highlight color (e.g., Tailwind blue-500) */
        z-index: -1; /* Place the circle behind the number */
    }

    .calendar-day.current-day span { /* The number inside the current day */
        position: relative; /* To ensure it's above the ::before pseudo-element */
        z-index: 2;
        color: white !important; /* White text color for the number */
    }

    /* Optional: Hover effect for active month days (excluding the current day) */
    .calendar-day.active-month:not(.current-day):hover {
        background-color: #cbd5e0; /* Tailwind's gray-300 (light gray on hover) */
        cursor: pointer;
    }
</style>

<div class="container mx-auto">
    <div class="mb-8">
        <h2 class="text-3xl font-semibold text-gray-800 mb-2">Welcome back, <?php echo htmlspecialchars($teacher_username); ?>!</h2>
        
    </div>

    <div class="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
        <div class="stat-card blue p-5 rounded-lg flex items-center space-x-4 shadow">
            <i class="fas fa-language text-3xl"></i>
            <div>
                <p class="text-sm font-medium opacity-80">TODAY'S LANGUAGE</p>
                <?php if ($current_language_name_for_selected_date_display === 'No language set for today') { ?>
                    <p class="text-xl font-bold">No language set</p>
                <?php } else { ?>
                    <p class="text-xl font-bold"><?php echo htmlspecialchars(explode('(', $current_language_name_for_selected_date_display)[0]); ?></p>
                <?php } ?>
            </div>
        </div>

        <div class="stat-card green p-5 rounded-lg flex items-center space-x-4 shadow">
            <i class="fas fa-globe text-3xl"></i>
            <div>
                <p class="text-sm font-medium opacity-80">AVAILABLE LANGUAGES</p>
                <p class="text-xl font-bold"><?php echo htmlspecialchars($total_languages); ?> Types</p>
            </div>
        </div>

        <div class="stat-card purple p-5 rounded-lg flex items-center space-x-4 shadow">
            <i class="fas fa-calendar-check text-3xl"></i>
            <div>
                <p class="text-sm font-medium opacity-80">DAYS SET THIS MONTH</p>
                <p class="text-xl font-bold"><?php echo htmlspecialchars($days_set_this_month); ?> Days</p>
            </div>
        </div>
    </div>

    <div class="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-8">
        <div class="lg:col-span-2 card">
            <div class="card-header">
                <h3 class="text-lg font-semibold text-gray-700">Quick Actions / To-Do</h3>
            </div>
            <div class="card-body space-y-4">
                <div class="p-4 bg-gray-50 rounded-lg border border-gray-200">
                    <h4 class="font-semibold text-gray-800 mb-1">Set Today's Language</h4>
                    <p class="text-gray-600 text-sm mb-3">Quickly jump to set or verify the language for today.</p>
                    <a href="teacher_dashboard.php?page=set_language" class="inline-block px-4 py-2 text-sm font-medium rounded-md bg-blue-600 text-white hover:bg-blue-700 transition-colors">Go to Settings</a>
                </div>
                <div class="p-4 bg-gray-50 rounded-lg border border-gray-200">
                    <h4 class="font-semibold text-gray-800 mb-1">View Usage Reports</h4>
                    <p class="text-gray-600 text-sm mb-3">Check analytics and reports on language usage.</p>
                    <a href="teacher_dashboard.php?page=language_usage" class="inline-block px-4 py-2 text-sm font-medium rounded-md bg-green-600 text-white hover:bg-green-700 transition-colors">View Reports</a>
                </div>
                <div class="p-4 bg-gray-50 rounded-lg border border-gray-200">
                    <h4 class="font-semibold text-gray-800 mb-1">Upcoming Feature</h4>
                    <p class="text-gray-600 text-sm">Student interaction log (Placeholder).</p>
                </div>
            </div>
        </div>

        <div class="lg:col-span-1 card">
            <div class="card-header flex justify-between items-center">
                <button id="prevMonth" class="p-2 rounded-full hover:bg-gray-100 text-gray-600"><i class="fas fa-chevron-left"></i></button>
                <h3 class="text-lg font-semibold text-gray-700" id="currentMonthYear"></h3>
                <button id="nextMonth" class="p-2 rounded-full hover:bg-gray-100 text-gray-600"><i class="fas fa-chevron-right"></i></button>
            </div>
            <div class="card-body">
                <div class="calendar-grid text-xs font-semibold text-gray-500 mb-2">
                    <div>Sun</div><div>Mon</div><div>Tue</div><div>Wed</div><div>Thu</div><div>Fri</div><div>Sat</div>
                </div>
                <div id="calendarDaysGrid" class="calendar-grid">
                    </div>
                <p class="text-xs text-gray-500 mt-4 text-center">View important dates or activity at a glance.</p>
            </div>
        </div>
    </div>

    <div class="card mb-8">
        <div class="card-header">
            <h3 class="text-lg font-semibold text-gray-700">Language Setting Trend</h3>
        </div>
        <div class="card-body">
            <div class="w-full h-72 bg-gray-100 rounded-lg flex items-center justify-center">
                <canvas id="languageTrendChart"></canvas>
            </div>
            <p class="text-xs text-gray-500 mt-2 text-center">This chart shows your language settings from Monday to Friday this week.</p>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
document.addEventListener('DOMContentLoaded', function() {
    // Chart.js initialization
    const ctx = document.getElementById('languageTrendChart');
    if (ctx) {
        new Chart(ctx, {
            type: 'bar',
            data: {
                // Dynamically set labels from PHP
                labels: <?php echo $chart_labels_json; ?>,
                // Dynamically set datasets from PHP
                datasets: <?php echo $chart_datasets_json; ?>
            },
            options: {
                responsive: true, maintainAspectRatio: false,
                scales: {
                    y: { beginAtZero: true, title: { display: true, text: 'Instances Set' }, ticks: { stepSize: 1 } },
                    x: { title: { display: true, text: 'Day of the Week' } }
                },
                plugins: { legend: { display: true, position: 'top' } }
            }
        });
    }

    // Calendar Logic
    const calendarDaysGrid = document.getElementById('calendarDaysGrid');
    const currentMonthYearEl = document.getElementById('currentMonthYear');
    const prevMonthBtn = document.getElementById('prevMonth');
    const nextMonthBtn = document.getElementById('nextMonth');

    if (calendarDaysGrid && currentMonthYearEl && prevMonthBtn && nextMonthBtn) {
        let calendarDate = new Date(); // This date object will be used to track the displayed month
        const today = new Date();     // This date object stores today's actual date for highlighting

        function renderCalendar() {
            calendarDaysGrid.innerHTML = ''; // Clear previous days
            const year = calendarDate.getFullYear();
            const month = calendarDate.getMonth(); // 0-indexed (January is 0)

            currentMonthYearEl.textContent = new Date(year, month).toLocaleString('en-US', { month: 'long', year: 'numeric' });

            const firstDayOfMonth = new Date(year, month, 1).getDay(); // 0 (Sun) to 6 (Sat)
            const daysInMonth = new Date(year, month + 1, 0).getDate(); // Days in current month
            const daysInPrevMonth = new Date(year, month, 0).getDate(); // Days in previous month

            // Add leading days from the previous month
            for (let i = 0; i < firstDayOfMonth; i++) {
                const dayElement = document.createElement('div');
                dayElement.classList.add('calendar-day', 'inactive-month');
                dayElement.innerHTML = `<span>${daysInPrevMonth - firstDayOfMonth + 1 + i}</span>`;
                calendarDaysGrid.appendChild(dayElement);
            }

            // Add days of the current month
            for (let day = 1; day <= daysInMonth; day++) {
                const dayElement = document.createElement('div');
                dayElement.innerHTML = `<span>${day}</span>`; // Wrap day number in a span
                dayElement.classList.add('calendar-day', 'active-month');

                // Highlight current day
                if (day === today.getDate() && month === today.getMonth() && year === today.getFullYear()) {
                    dayElement.classList.add('current-day');
                }
                calendarDaysGrid.appendChild(dayElement);
            }

            // Add trailing days from the next month to fill the grid (typically 6 rows = 42 cells)
            const totalCellsInGrid = 42; // Standard 6 rows * 7 days
            const currentRenderedCells = firstDayOfMonth + daysInMonth;
            const remainingCellsToFill = totalCellsInGrid - currentRenderedCells;

            for (let i = 1; i <= remainingCellsToFill; i++) {
                const dayElement = document.createElement('div');
                dayElement.classList.add('calendar-day', 'inactive-month');
                dayElement.innerHTML = `<span>${i}</span>`;
                calendarDaysGrid.appendChild(dayElement);
            }
        }

        prevMonthBtn.addEventListener('click', () => {
            calendarDate.setMonth(calendarDate.getMonth() - 1);
            renderCalendar();
        });

        nextMonthBtn.addEventListener('click', () => {
            calendarDate.setMonth(calendarDate.getMonth() + 1);
            renderCalendar();
        });

        renderCalendar(); // Initial render of the calendar
    } else {
        console.warn("One or more calendar elements (calendarDaysGrid, currentMonthYear, prevMonth, nextMonth) not found in the DOM.");
    }
});
</script>